[package]
name = "heliochrome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.2"
wgpu = "0.13.1"
env_logger = "0.9.0"
pollster = "0.2.5"