[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heliochrome = { path = "../heliochrome" }
indicatif = "0.17.0"
softbuffer = "0.1.1"
eframe = "0.21.3"
egui_dock = "0.5"
